### ISSUE TITLE
i will love to do copywriting for you 

### ISSUE THREAD

**Issue by Hamzeto938** [rayano24/calculatorApp#2]
I love your application and would want to contribute to it, I'm not a developer but I am good at copywriting. I would love to make a copywrite for your Readme and make a pull request for you to merge. Your response would be highly appreciated. Also I would like to request if we could communicate via email, so I don't have to create issues. Thank you.

**Comment by rayano24** [comment]
Hi Hamze, thank you for the offer. This is a really simple calculator app that I am doing to learn Android Studio so I don't think there is really a need for further docs. However, the projects I will be working on next could benefit from this, so I'll be sure to keep you in mind! Thanks!
